import type { Metadata } from "next";

// Imported fonts from fonts module
import { geistMono, geistSans } from "@/lib/fonts";
// Css Configurations
import "./globals.css";
// Entire App data
import { appData } from "@/lib/data";
// Providers
import HeroProvider from "@/lib/providers/HeroProvider";

export const metadata: Metadata = {
  title: appData.name,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeroProvider>{children}</HeroProvider>
      </body>
    </html>
  );
}
