import type { Metadata } from "next";

// Imported fonts from fonts module
import { geistMono, geistSans } from "@/lib/fonts";
// Css Configurations
import "@/app/globals.css";
// Entire App data
import { appData } from "@/lib/data";
// Providers
import AppProvider from "@/lib/providers/Provider";
// UI
import Navigation from "@/components/navigation";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: appData.name,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          <Navigation />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
